require 'rspec/core/rake_task'

task :default => [:spec] # [:compile, :spec]

desc "Run all specs"
RSpec::Core::RakeTask.new do |t|
	t.pattern = 'spec/**/*_spec.rb'
	t.rspec_opts = '-fd'
	#t.ruby_opts = '-w'
end
